---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"
    use: "debian"

- name: Replace /etc/hosts
  ansible.builtin.template:
    src: "hosts.j2"
    dest: "/etc/hosts"
    owner: "root"
    group: "root"
    mode: 0644

- name: Set authorized_keys
  ansible.posix.authorized_key:
    user: "asivula"
    key: "{{ lookup('file', pipeline_pubkey) }}"

- name: Install common packages
  ansible.builtin.apt:
    name:
      - curl
      - man
      - telnet
      - vim

