---
- name: Set hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Set authorized_keys
  ansible.posix.authorized_key:
    user: "asivula"
    key: "{{ lookup('file', pipeline_pubkey) }}"

- name: Add 'asivula' to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: '^asivula'
    line: 'asivula ALL=(ALL) NOPASSWD: ALL'
    backup: yes
    validate: /usr/sbin/visudo -cf %s

