# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define :scm do |scm|
    scm.vm.box = "ubuntu/focal64"
    scm.vm.network :private_network, ip: "192.168.56.10"

    scm.vm.provider :virtualbox do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
  end

end
