---
- name: Install dependencies
  package:
    name:
      - iptables
      - iptables-persistent
    state: present

- name: Replace configuration file
  template:
    src: templates/rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: '0644'
    validate: 'sudo /usr/sbin/iptables-restore -t %s'
  notify:
    - Reload iptables configuration

