- name: Install BIND and utils
  ansible.builtin.apt:
    name:
      - bind9
      - bind9-utils
      - bind9-dnsutils
    update_cache: yes

- name: Configure BIND (named) to run IPv4 only
  ansible.builtin.lineinfile:
    path: "/etc/default/named"
    regexp: 'OPTIONS="-u bind"'
    line: 'OPTIONS="-4 -u bind"'
    state: present

- name: Make sure BIND working directory exists
  ansible.builtin.file:
    state: directory
    path: "/var/bind/cache"
    owner: bind
    group: bind
    mode: 0755

- name: Make sure zone file directory exists
  ansible.builtin.file:
    state: directory
    path: "/etc/bind/zones"
    owner: root
    group: bind
    mode: 0755

- name: Make sure /var/log/named exists
  ansible.builtin.file:
    state: directory
    path: "/var/log/named"
    owner: root
    group: bind
    mode: 0775

- name: Replace BIND named configuration
  ansible.builtin.template:
    src: "named.conf.options.j2"
    dest: "/etc/bind/named.conf.options"
    owner: "root"
    group: "bind"
    mode: 0644


- name: Create forward zone file
  ansible.builtin.template:
    src: "forward.vm.kre.j2"
    dest: "{{ dns_forward_record_file }}"
    owner: root
    group: bind
    mode: 0640

- name: Create reverse zone file
  ansible.builtin.template:
    src: "reverse.vm.kre.j2"
    dest: "{{ dns_reverse_record_file }}"
    owner: root
    group: bind
    mode: 0640

- name: Check that BIND configuration is correct
  ansible.builtin.command:
    cmd: "named-checkconf"
  changed_when: false

- name: Check the forward zone
  ansible.builtin.command:
    cmd: "named-checkzone {{ vms.domain }} {{ dns_forward_record_file }}"
  changed_when: false

- name: Check the reverse zone
  ansible.builtin.command:
    cmd: "named-checkzone {{ vms.domain }} {{ dns_reverse_record_file }}"
  changed_when: false

- name: Restart named
  ansible.builtin.systemd:
    name: named
    state: restarted

- name: Replace /etc/resolv.conf file
  ansible.builtin.template:
    src: "resolv.conf.j2"
    dest: "/etc/resolv.conf"
    owner: root
    group: root
    mode: 0644

